version: '3.3'

services:
  php:
    build:
      context: ./
      args:
        - USER_ID=${CURRENT_UID:-1000}
        - GROUP_ID=${CURRENT_GID:-1000}
    container_name: time_tracker_php
    restart: 'no'
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - 8000:8000
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql
      - phpmyadmin
    volumes:
      - .:/var/www/symfony
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./config/nginx/fpm-pool.conf:/usr/local/etc/php-fpm.d/fpm-pool.conf

  mysql:
    image: mariadb:10.11
    container_name: time_tracker_mysql
    restart: 'no'
    command: '--sql_mode="" --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856'
    volumes:
      - ./config/mysql/mariadb.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: time_tracker_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
